-- 既存のテーブルを安全に削除
DROP TABLE IF EXISTS public.word_occurrences;
DROP TABLE IF EXISTS public.unique_words;
DROP TABLE IF EXISTS public.crawled_urls;
DROP TABLE IF EXISTS public.stop_words;
DROP TABLE IF EXISTS public.crawl_queue;
DROP TYPE IF EXISTS public.crawl_status;

-- 1. URLの状態を定義 (キュー、処理中、完了、失敗)
CREATE TYPE public.crawl_status AS ENUM ('queued', 'processing', 'completed', 'failed');

-- 2. クロール対象のURLを管理する中央キューテーブル
CREATE TABLE public.crawl_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL UNIQUE,
  status public.crawl_status NOT NULL DEFAULT 'queued',
  discovered_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  processed_at TIMESTAMPTZ,
  error_message TEXT
);
-- アクセス権を設定
ALTER TABLE public.crawl_queue ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON public.crawl_queue FOR ALL USING (true) WITH CHECK (true);

-- 3. 除外単語テーブル (変更なし)
CREATE TABLE public.stop_words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word TEXT NOT NULL UNIQUE,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
ALTER TABLE public.stop_words ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON public.stop_words FOR ALL USING (true) WITH CHECK (true);

-- 4. ユニーク単語テーブル (変更なし)
CREATE TABLE public.unique_words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word TEXT NOT NULL UNIQUE,
  pos TEXT,
  discovered_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
ALTER TABLE public.unique_words ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON public.unique_words FOR ALL USING (true) WITH CHECK (true);

-- 5. 単語の出現場所テーブル (変更なし)
CREATE TABLE public.word_occurrences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word_id BIGINT NOT NULL REFERENCES public.unique_words(id) ON DELETE CASCADE,
  source_url TEXT NOT NULL,
  CONSTRAINT unique_occurrence UNIQUE (word_id, source_url)
);
ALTER TABLE public.word_occurrences ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON public.word_occurrences FOR ALL USING (true) WITH CHECK (true);
