/**
 * 1. 処理済みURLを記録するテーブル
 * 一定期間が経過したレコードはスクリプトによって削除され、再クロールの対象となります。
 */
CREATE TABLE public.crawled_urls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL UNIQUE,
  crawled_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- テーブルへのアクセス権を設定
ALTER TABLE public.crawled_urls ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON public.crawled_urls FOR ALL USING (true) WITH CHECK (true);


/**
 * 2. 発見した新語を格納するテーブル
 */
CREATE TABLE public.new_words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word TEXT NOT NULL,
  pos TEXT, -- 品詞 (例: 名詞,普通名詞,*,*)
  source_url TEXT NOT NULL,
  discovered_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  -- 同じ単語とURLの組み合わせは重複して登録しないようにUNIQUE制約を設定
  CONSTRAINT unique_word_per_url UNIQUE (word, source_url)
);

-- テーブルへのアクセス権を設定
ALTER TABLE public.new_words ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON public.new_words FOR ALL USING (true) WITH CHECK (true);
