-- =========== 最終版 セットアップSQL (修正案) ============
-- 既存の全オブジェクトを依存関係を考慮して安全に削除
DROP TABLE IF EXISTS public.word_occurrences CASCADE;
DROP TABLE IF EXISTS public.unique_words CASCADE;
DROP TABLE IF EXISTS public.sentence_queue CASCADE;
DROP TABLE IF EXISTS public.crawl_queue CASCADE;
DROP TABLE IF EXISTS public.stop_words CASCADE;
DROP TABLE IF EXISTS public.boilerplate_patterns CASCADE; -- 追加
DROP TYPE IF EXISTS public.process_status_enum;

-- 1. 処理状態を定義する型
CREATE TYPE public.process_status_enum AS ENUM ('queued', 'processing', 'completed', 'failed');

-- 2. URLを管理するクロールキュー
CREATE TABLE public.crawl_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL UNIQUE,
  extraction_status public.process_status_enum NOT NULL DEFAULT 'queued',
  content_hash TEXT,
  last_modified TEXT,
  etag TEXT,
  processed_at TIMESTAMPTZ
);

-- 3. 抽出されたテキストを管理するテキストキュー
CREATE TABLE public.sentence_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crawl_queue_id BIGINT NOT NULL REFERENCES public.crawl_queue(id) ON DELETE CASCADE,
  sentence_text TEXT NOT NULL,
  ginza_status public.process_status_enum NOT NULL DEFAULT 'queued',
  stanza_status public.process_status_enum NOT NULL DEFAULT 'queued'
);

-- 4. 新語発見結果を保存するテーブル
CREATE TABLE public.unique_words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word TEXT NOT NULL,
  source_tool TEXT NOT NULL,
  entity_category TEXT,
  pos_tag TEXT,
  discovered_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT unique_word_per_tool UNIQUE (word, source_tool)
);

CREATE TABLE public.word_occurrences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word_id BIGINT NOT NULL REFERENCES public.unique_words(id) ON DELETE CASCADE,
  source_url TEXT NOT NULL,
  CONSTRAINT unique_occurrence UNIQUE (word_id, source_url)
);

-- 5. ストップワードテーブル
CREATE TABLE public.stop_words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word TEXT NOT NULL UNIQUE,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 6. 不要な定型文（ボイラープレート）を管理するテーブル (--- ここから追加 ---)
CREATE TABLE public.boilerplate_patterns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pattern TEXT NOT NULL UNIQUE,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
-- (--- ここまで追加 ---)