-- 6. 不要な定型文（ボイラープレート）を管理するテーブル (--- ここから追加 ---)
CREATE TABLE public.boilerplate_patterns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pattern TEXT NOT NULL UNIQUE,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
-- (--- ここまで追加 ---)