-- === 移行用SQL (`stop_words`データのみ維持) ===

-- ステップ1: 既存の`stop_words`テーブルを一時的な名前に変更して保護
ALTER TABLE IF EXISTS public.stop_words RENAME TO stop_words_backup;

-- ステップ2: 他のすべての関連テーブルを完全に削除
DROP TABLE IF EXISTS public.word_occurrences;
DROP TABLE IF EXISTS public.unique_words;
DROP TABLE IF EXISTS public.crawl_queue;
DROP TYPE IF EXISTS public.crawl_status;
DROP TABLE IF EXISTS public.crawled_urls;

-- ステップ3: 最新のスキーマで全テーブルを新規作成
-- 3-1. URL状態の型を定義
CREATE TYPE public.crawl_status AS ENUM ('queued', 'processing', 'completed', 'failed');

-- 3-2. 中央キューテーブル
CREATE TABLE public.crawl_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL UNIQUE,
  status public.crawl_status NOT NULL DEFAULT 'queued',
  content_hash TEXT,
  discovered_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  processed_at TIMESTAMPTZ,
  error_message TEXT
);
ALTER TABLE public.crawl_queue ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON public.crawl_queue FOR ALL USING (true) WITH CHECK (true);

-- 3-3. stop_wordsテーブル (新しい空のテーブル)
CREATE TABLE public.stop_words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word TEXT NOT NULL UNIQUE,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
ALTER TABLE public.stop_words ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON public.stop_words FOR ALL USING (true) WITH CHECK (true);

-- 3-4. unique_wordsテーブル
CREATE TABLE public.unique_words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word TEXT NOT NULL UNIQUE,
  pos TEXT,
  discovered_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
ALTER TABLE public.unique_words ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON public.unique_words FOR ALL USING (true) WITH CHECK (true);

-- 3-5. word_occurrencesテーブル
CREATE TABLE public.word_occurrences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word_id BIGINT NOT NULL REFERENCES public.unique_words(id) ON DELETE CASCADE,
  source_url TEXT NOT NULL,
  CONSTRAINT unique_occurrence UNIQUE (word_id, source_url)
);
ALTER TABLE public.word_occurrences ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON public.word_occurrences FOR ALL USING (true) WITH CHECK (true);


-- ステップ4: バックアップから新しい`stop_words`テーブルにデータを復元
INSERT INTO public.stop_words (word, reason, created_at)
SELECT word, reason, created_at FROM public.stop_words_backup;


-- ステップ5: バックアップ用テーブルを削除して完了
DROP TABLE public.stop_words_backup;
