# .github/workflows/process-only-pipeline.yml
name: Process NLP Queue (Scheduled)

on:
#  schedule:
    # 3, 15, 21 UTC (日本時間 12:00, 00:00, 06:00) に実行
#    - cron: '0 3,15,21 * * *'
  workflow_dispatch:

jobs:
  process_ginza:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        instance: [1, 2]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - name: Install GiNZA and dependencies
        run: |
          pip install -U ginza ja_ginza_electra
          pip install requests beautifulsoup4 supabase configparser
      - name: Run GiNZA Processor (Instance ${{ matrix.instance }})
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python process_ginza.py

  process_stanza:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        instance: [1, 2]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - name: Install Stanza and dependencies
        run: |
          pip install "numpy<2.0" stanza
          pip install requests beautifulsoup4 supabase configparser
      - name: Pre-download Stanza model
        run: |
          python -c "import stanza; stanza.download('ja', verbose=False)"
      - name: Run Stanza Processor (Instance ${{ matrix.instance }})
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python process_stanza.py
